site_name: tomoCodes
nav:
  - '剑指offer/index.md'
  - '剑指offer专项版/index.md'
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: blue grey
  language: zh
plugins:
  - search:
      lang: ja
  - tags:
      tags_file: tags.md
